name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: issue-description 
    attributes:
      label: Issue Description
      description: Describe the issue encountered
      placeholder: Tell us what you see!
      # value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: duplicate-steps
    attributes:
      label: Duplicate Steps 
      description: Describe the actions that triggered the issue
      placeholder: Tell us what you did!
      # value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: expected-results
    attributes:
      label: Expected Results
      description: Describe what it supposed to happen instead
      placeholder: Tell us what you expect!
      # value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version-detected
    attributes:
      label: Version Detected
      description: What version of SRA tool are you running?
      options:
        - 1.0.1 (Default)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
